name: 'Setup Kubelogin'
description: 'Install Kubelogin with a specific version'
inputs:
  version:
    description: 'version of Kubelogin binary'
    default: 'v1.27.0'
runs:
  using: "composite"
  steps:
    - name: Download Kubelogin
      uses: bash
      run: |
        curl -LO "https://github.com/int128/kubelogin/releases/download/${{ inputs.version }}/kubelogin_linux_amd64.zip"
        unzip -j "kubelogin_linux_amd64.zip" -d /tmp/kubelogin
        sudo mv /tmp/kubelogin/kubelogin /usr/local/bin/kubectl-oidc_login
        rm -f "kubelogin_linux_amd64.zip"
        kubectl oidc-login --version
